<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="Jasa pembuatan website profesional untuk sekolah dan lembaga pendidikan.">
    <title>{{ $settings['brand'] ?? 'EduWeb Studio' }} — Website Sekolah Profesional</title>
    <link rel="icon" type="image/svg+xml" href="{{ asset('favicon.svg') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Manrope:wght@500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('css/landing-v2.css') }}">
    <link rel="stylesheet" href="{{ asset('css/logo-fix.css') }}">
    <link rel="stylesheet" href="{{ asset('css/floating-whatsapp.css') }}">
    <script src="{{ asset('js/floating-whatsapp.js') }}" defer></script>
</head>
<body>
@php($heroProject = ($items['portfolio'] ?? collect())->first())

<nav class="nav" id="nav"><div class="shell nav-inner"><a class="logo" href="#home"><span class="logo-mark">E</span><span>{{ $settings['brand'] ?? 'EduWeb Studio' }}</span></a><div class="nav-menu" id="navMenu"><a href="#layanan">Layanan</a><a href="#portofolio">Portofolio</a><a href="#proses">Proses</a><a href="#harga">Harga</a><a href="#faq">FAQ</a></div><a class="nav-cta" href="#kontak">Konsultasi <span>↗</span></a><button class="menu-toggle" id="menuToggle" aria-label="Buka menu"><i></i><i></i></button></div></nav>

<main>
<header class="hero" id="home"><div class="hero-glow"></div><div class="shell hero-wrap"><div class="hero-copy fade"><div class="kicker"><span></span>{{ $settings['hero_badge'] ?? 'Spesialis Website Pendidikan' }}</div><h1>Website sekolah yang <span>berkelas, dipercaya,</span> dan mudah dikelola.</h1><p>{{ $settings['hero_text'] ?? '' }}</p><div class="hero-actions"><a class="btn btn-accent" href="#kontak">Mulai konsultasi <b>↗</b></a><a class="btn btn-ghost" href="#portofolio">Lihat portofolio</a></div><div class="hero-trust"><div><strong>50+</strong><span>Proyek pendidikan</span></div><div><strong>4.9/5</strong><span>Kepuasan klien</span></div><div><strong>99%</strong><span>Website uptime</span></div></div></div><div class="hero-media fade delay"><div class="media-head"><span>Featured project</span><b>{{ $heroProject?->title ?? 'Website Sekolah' }}</b></div><div class="device"><div class="device-bar"><span><i></i><i></i><i></i></span><small>website-sekolah.sch.id</small><b>•••</b></div>@if($heroProject?->image_path)<img src="{{ asset('storage/'.$heroProject->image_path) }}" alt="{{ $heroProject->title }}">@endif</div><div class="media-foot"><span>{{ $heroProject?->subtitle }}</span><a href="{{ $heroProject ? route('portfolio.demo',$heroProject) : '#portofolio' }}">Lihat studi kasus ↗</a></div></div></div><div class="shell hero-bottom"><span>Dipercaya lembaga pendidikan di Indonesia</span><div><b>SEKOLAHKU</b><b>EDUCARE</b><b>AKADEMIA</b><b>GENCER</b></div></div></header>

<section class="section intro" id="layanan"><div class="shell"><div class="section-heading fade"><div><span class="eyebrow">01 / Keahlian kami</span><h2>Satu partner untuk seluruh<br>kebutuhan <span>digital sekolah.</span></h2></div><p>Kami menggabungkan strategi, desain, dan teknologi untuk menghadirkan website yang bukan hanya terlihat baik, tetapi benar-benar membantu sekolah bekerja.</p></div><div class="services">@foreach($items['services'] ?? [] as $item)<article class="service fade"><span class="service-no">{{ str_pad($loop->iteration,2,'0',STR_PAD_LEFT) }}</span><div class="service-icon">{{ $item->icon }}</div><h3>{{ $item->title }}</h3><p>{{ $item->description }}</p><i>↗</i></article>@endforeach</div></div></section>

<section class="section portfolio" id="portofolio"><div class="shell"><div class="section-heading light fade"><div><span class="eyebrow">02 / Karya pilihan</span><h2>Setiap sekolah punya<br><span>cerita yang berbeda.</span></h2></div><p>Karena itu kami tidak menggunakan satu template untuk semua. Setiap proyek dirancang sesuai karakter dan tujuan institusi.</p></div><div class="projects">@foreach($items['portfolio'] ?? [] as $item)<article class="project fade"><div class="project-image">@if($item->image_path)<img src="{{ asset('storage/'.$item->image_path) }}" alt="Preview {{ $item->title }}">@endif<div class="project-index">0{{ $loop->iteration }}</div></div><div class="project-info"><div><span>{{ $item->subtitle }}</span><h3>{{ $item->title }}</h3></div><p>{{ $item->description }}</p><span class="project-arrow" aria-hidden="true">↗</span></div></article>@endforeach</div></div></section>

<section class="section value"><div class="shell value-grid"><div class="value-lead fade"><span class="eyebrow">03 / Nilai lebih</span><h2>Teknologi yang rumit,<br>kami buat <span>sederhana.</span></h2><p>Tim sekolah tidak perlu memahami coding untuk memperbarui berita, halaman, atau informasi penting.</p><a href="#kontak">Diskusikan kebutuhan Anda →</a></div><div class="feature-list">@foreach($items['features'] ?? [] as $item)<article class="feature fade"><span>{{ $item->icon }}</span><div><h3>{{ $item->title }}</h3><p>{{ $item->description }}</p></div></article>@endforeach</div></div></section>

<section class="metrics"><div class="shell metric-grid"><div><strong>50<sup>+</sup></strong><span>Website selesai</span></div><div><strong>7<sup>hari</sup></strong><span>Dukungan aktif</span></div><div><strong>99<sup>%</sup></strong><span>Uptime website</span></div><div><strong>4.9<sup>/5</sup></strong><span>Rata-rata kepuasan</span></div></div></section>

<section class="section process" id="proses"><div class="shell"><div class="section-heading fade"><div><span class="eyebrow">04 / Proses kerja</span><h2>Transparan dari awal<br>hingga <span>website tayang.</span></h2></div><p>Anda selalu mengetahui progres proyek dan terlibat pada setiap keputusan penting.</p></div><div class="steps">@foreach($items['process'] ?? [] as $item)<article class="step fade"><div><span>{{ $item->icon }}</span><i></i></div><h3>{{ $item->title }}</h3><p>{{ $item->description }}</p></article>@endforeach</div></div></section>

<section class="section pricing" id="harga"><div class="shell"><div class="section-heading fade"><div><span class="eyebrow">05 / Investasi</span><h2>Pilih fondasi yang tepat<br>untuk <span>sekolah Anda.</span></h2></div><p>Semua paket dapat disesuaikan. Biaya dan lingkup kerja selalu disepakati sebelum proyek dimulai.</p></div><div class="plans">@foreach($items['pricing'] ?? [] as $item)<article class="plan {{ $loop->iteration===2?'popular':'' }} fade">@if($loop->iteration===2)<span class="popular-badge">Rekomendasi</span>@endif<div class="plan-head"><span>0{{ $loop->iteration }}</span><h3>{{ $item->title }}</h3><p>{{ $item->description }}</p></div><div class="plan-price"><small>Mulai dari</small><strong>{{ $item->price }}</strong><span>/ proyek</span></div><ul>@foreach($item->meta['features'] ?? [] as $feature)<li><i>✓</i>{{ $feature }}</li>@endforeach</ul><a href="#kontak">Konsultasikan <b>↗</b></a></article>@endforeach</div></div></section>

<section class="testimonial"><div class="shell quote fade"><span class="quote-icon">“</span>@foreach($items['testimonials'] ?? [] as $item)<blockquote>{{ $item->description }}</blockquote><div class="quote-person"><b>{{ strtoupper(substr($item->title,0,1)) }}</b><p><strong>{{ $item->title }}</strong><span>{{ $item->subtitle }}</span></p></div>@break @endforeach</div></section>

<section class="section faq" id="faq"><div class="shell faq-grid"><div class="faq-title fade"><span class="eyebrow">06 / FAQ</span><h2>Hal yang sering<br><span>ditanyakan.</span></h2><p>Belum menemukan jawaban yang Anda butuhkan? Tim kami siap membantu.</p><a href="#kontak">Tanya langsung →</a></div><div class="accordions">@foreach($items['faqs'] ?? [] as $item)<article class="accordion {{ $loop->first?'open':'' }} fade"><button><span>{{ $item->title }}</span><i></i></button><div><p>{{ $item->description }}</p></div></article>@endforeach</div></div></section>

<section class="contact" id="kontak"><div class="shell contact-box fade"><div class="contact-copy"><span class="eyebrow">Mulai proyek Anda</span><h2>{{ $settings['cta_title'] ?? 'Mari membangun website sekolah Anda.' }}</h2><p>{{ $settings['cta_text'] ?? '' }}</p><div><small>Kontak langsung</small><a href="https://wa.me/{{ $settings['whatsapp'] ?? '' }}" target="_blank">+{{ $settings['whatsapp'] ?? '' }}</a><a href="mailto:{{ $settings['email'] ?? '' }}">{{ $settings['email'] ?? '' }}</a></div></div><div class="contact-form">@if(session('success'))<div class="notice success">{{ session('success') }}</div>@endif @if($errors->any())<div class="notice error">{{ $errors->first() }}</div>@endif<form method="post" action="{{ route('inquiries.store') }}">@csrf<div class="form-row"><label>Nama lengkap<input name="name" value="{{ old('name') }}" required placeholder="Nama Anda"></label><label>Nama institusi<input name="school" value="{{ old('school') }}" placeholder="Nama sekolah"></label></div><div class="form-row"><label>WhatsApp<input name="phone" value="{{ old('phone') }}" required placeholder="08xx xxxx xxxx"></label><label>Email<input type="email" name="email" value="{{ old('email') }}" placeholder="nama@sekolah.sch.id"></label></div><label>Ceritakan kebutuhan Anda<textarea name="message" rows="4" required placeholder="Website profil, PPDB online, portal sekolah...">{{ old('message') }}</textarea></label><button type="submit">Kirim permintaan <span>↗</span></button></form></div></div></section>
</main>

<footer><div class="shell footer-main"><div><a class="logo" href="#home"><span class="logo-mark">E</span><span>{{ $settings['brand'] ?? 'EduWeb Studio' }}</span></a><p>Website profesional untuk pendidikan Indonesia.</p></div><div><small>Navigasi</small><a href="#layanan">Layanan</a><a href="#portofolio">Portofolio</a><a href="#harga">Harga</a></div><div><small>Kontak</small><a href="mailto:{{ $settings['email'] ?? '' }}">{{ $settings['email'] ?? '' }}</a><span>{{ $settings['address'] ?? '' }}</span></div></div><div class="shell footer-bottom"><span>© {{ date('Y') }} {{ $settings['brand'] ?? 'EduWeb Studio' }}</span><span>Designed for better education.</span><a href="{{ route('login') }}">Admin</a></div></footer>

<script>const nav=document.getElementById('nav'),toggle=document.getElementById('menuToggle'),menu=document.getElementById('navMenu');addEventListener('scroll',()=>nav.classList.toggle('scrolled',scrollY>20));toggle.onclick=()=>{toggle.classList.toggle('active');menu.classList.toggle('active')};document.querySelectorAll('.nav-menu a').forEach(a=>a.onclick=()=>{toggle.classList.remove('active');menu.classList.remove('active')});document.querySelectorAll('.accordion button').forEach(b=>b.onclick=()=>{const item=b.parentElement;document.querySelectorAll('.accordion').forEach(x=>x!==item&&x.classList.remove('open'));item.classList.toggle('open')});const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');io.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.fade').forEach(e=>io.observe(e));</script>
</body></html>
